{{- if and (include "normalizeBoolean" .Values.ingress.enabled | fromYaml) (include "normalizeBoolean" .Values.ingress.nginx.enabled | fromYaml) (not (include "normalizeBoolean" .Values.ingress.otc.enabled | fromYaml)) (not (include "normalizeBoolean" .Values.ingress.tls.enabled | fromYaml)) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress

spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              service:
                name: {{ .Values.name }}-svc
                port:
                  number: {{ .Values.service.ports.http }}
            pathType: Prefix
{{- end }}
