# OTC ingress spec: https://docs.otc.t-systems.com/cloud-container-engine/umn/network/ingresses/loadbalancer_ingresses/using_kubectl_to_create_a_loadbalancer_ingress.html
{{- $ingressEnabled := (include "booleanToStringValue" (dict "value" .Values.ingress.enabled)) | trim }}
{{- $nginxEnabled := (include "booleanToStringValue" (dict "value" .Values.ingress.nginx.enabled)) | trim }}
{{- $otcEnabled := (include "booleanToStringValue" (dict "value" .Values.ingress.otc.enabled)) | trim }}
{{- $tlsEnabled := (include "booleanToStringValue" (dict "value" .Values.ingress.tls.enabled)) | trim }}

{{- if and (eq $ingressEnabled "true") (eq $otcEnabled "true") (eq $tlsEnabled "false") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  annotations:
    kubernetes.io/elb.port: {{ .Values.ingress.port | quote }}

    {{- if .Values.ingress.otc.autocreate }}
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate:
      '{
          "name":"{{ .Values.name }}-elb",
          "type":"public",
          "bandwidth_name":"codbex-rhea-bandwidth",
          "bandwidth_chargemode":"traffic",
          "bandwidth_size":5,
          "bandwidth_sharetype":"PER",
          "eip_type":"5_bgp"
        }'
    {{- end }}

    {{- if not .Values.ingress.otc.autocreate }}
    kubernetes.io/elb.id: {{ .Values.ingress.otc.existingELB.id }} # Load balancer ID
    kubernetes.io/elb.class: {{ .Values.ingress.otc.existingELB.class }}   # Load balancer type
    {{- end }}

spec:
  {{- if and (eq $ingressEnabled "true") (eq $otcEnabled "true") }}
  ingressClassName: cce
  {{- end }}

  {{- if and (eq $ingressEnabled "true") (eq $nginxEnabled "true") }}
  ingressClassName: nginx
  {{- end }}

  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              service:
                name: {{ .Values.name }}-svc
                port:
                  number: {{ .Values.service.ports.http }}
            pathType: Prefix
{{- end }}
